-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Asiakas CASCADE; 
DROP TABLE IF EXISTS Tyontekija CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE; 
DROP TABLE IF EXISTS Tayte CASCADE;
DROP TABLE IF EXISTS Pizzatayte CASCADE;
DROP TABLE IF EXISTS Tilaus CASCADE; 